/// <reference types="vite/client" />

interface TrackmanData {
  [key: keyof TrackmanData | string]: string
  PitchNo: string
  PAofInning: string
  PitchofPA: string
  Pitcher: string
  PitcherThrows: string
  PitcherTeam: string
  Batter: string
  BatterSide: string
  BatterTeam: string
  PitcherSet: string
  Inning: string
  'Top/Bottom': string
  Outs: string
  Balls: string
  Strikes: string
  TaggedPitchType: string
  AutoPitchType: string
  PitchCall: string
  KorBB: string
  HitType: string
  PlayResult: string
  OutsOnPlay: string
  RunsScored: string
  Notes: string
  RelSpeed: string
  VertRelAngle: string
  HorzRelAngle: string
  SpinRate: string
  SpinAxis: string
  Tilt: string
  RelHeight: string
  RelSide: string
  Extension: string
  VertBreak: string
  InducedVertBreak: string
  HorzBreak: string
  PlateLocHeight: string
  PlateLocSide: string
  ZoneSpeed: string
  VertApprAngle: string
  HorzApprAngle: string
  ZoneTime: string
  ExitSpeed: string
  Angle: string
  Direction: string
  HitSpinRate: string
  PositionAt110X: string
  PositionAt110Y: string
  PositionAt110Z: string
  Distance: string
  LastTrackedDistance: string
  Bearing: string
  HangTime: string
  pfxx: string
  pfxz: string
  x0: string
  y0: string
  z0: string
  vx0: string
  vy0: string
  vz0: string
  ax0: string
  ay0: string
  az0: string
}
